### ISSUE TITLE
“薩”字形

### ISSUE THREAD

**Issue by garfieldLSY** [enderseven1/Mizuki-Gothic#1]
水木黑體中“薩”仍然是舊字形。

**Comment by enderseven1** [comment]
水木系列字体主打印刷体风格，反对楷化，因为楷化对宋体（明体）字的观感影响很大，但是黑体楷化并没有较大影响，甚至可能更美观，而且水木系列是针对简体字的，繁体字不一定顾及。水木黑体由于优先度低、使用人数过少、需求不大，以及我个人的原因，已经停止维护，但未归档。
如果你希望更正，可以fork后改正，之后pull给我。感谢您支持水木字型。可以加入我们的QQ群一起交流：901505967。在修正薩字形以后，我大概率不会再发布任何更新。
